### ISSUE TITLE
sec-trial.html 4.1.2

### ISSUE THREAD

**Issue by themeo** [vasishth/bayescogsci#10]
These are tiny issues:

> In order to understand the type of data that we are assuming a priori with the prior of the parameter  
β , we’ll plot the closely related, but more intuitive median difference between the effects at adjacent trials.

I wasn't sure "closely related" to what? Closely related to the mean? 

---

> To plot the median effect, we first define a function that calculates the difference between adjacent trials, and then applies the median to the result.

I presume the focus on the difference between adjacent trials is related to our interest in the effect of `c_trial` but perhaps it could be made more explicit in the description, i.e. that we want to estimate the effect c_trial in each pair of adjacent trials. 

--- 

> As expected, it is centered on zero (as our prior), but we see that the distribution of possible medians for the effect is too widely spread out and includes values that are too extreme.

The bars on the histogram in Fig 4.5 do not show extreme effects, it has to be inferred from the range of x-values which were automatically plotted -- I guess it may be confusing to many people. Similarly, the difference with the next figure consists mainly in the change of x-scale.

**Comment by bnicenboim** [comment]
just fixed the first one, issue 2 and 3 still need to be fixed
