### ISSUE TITLE
sec-N400hierarchical.html 

### ISSUE THREAD

**Issue by themeo** [vasishth/bayescogsci#11]
**5.1.3.2 Likelihood and priors**
The order of subscripts for u is mixed in the model specification and in the text: u_{subj[n],1} vs u_{1,subj}

---

**Figure 5.10**
in caption: blue->green. It could perhaps help some readers to be reminded that all green lines are drawn from the same distribution (even though they differ across the panels).

**Comment by bnicenboim** [comment]
thanks!
(I've done the first part.)

Not sure if I understand the last part. This is the caption:
 The plot shows 100 predicted distributions in blue density plots and the distribution of the average signal data in black density plots for the 37 subjects that participated in the experiment. 

They are not the same distribution, we assume differences between subjects. All of them have the same sd, though.
