### ISSUE TITLE
regression-models-in-stan.html code in section 10.4.1

### ISSUE THREAD

**Issue by themeo** [vasishth/bayescogsci#12]
I think there is an error in Stan code in section `generated quantities`:

```stan
generated quantities {
  real p_size_pred[N];
  p_size_pred = normal_rng(alpha + c_load * beta, sigma);
}
```

Shouldn't `p_size_pred` also be indexed in the 2nd line?

**Comment by bnicenboim** [comment]
it's vectorized
that would work like in Stan
