### ISSUE TITLE
https://vasishth.github.io/bayescogsci/book/ch-remame.html

### ISSUE THREAD

**Issue by themeo** [vasishth/bayescogsci#14]
> The main parameter of interest is usually ζ , but τ

I think "not" might be missing. 

I was also surprised by:
> τ, which quantifies between-study variability or the noise in the measurement process

We didn't use the between-study context/example before. It totally makes sense in the context of metaanalysis but not in the context of measurement error which was also discussed above, so it might make sense to qualify this.

**Comment by bnicenboim** [comment]
thanks! the not wasn't missing, but the sentence was weird.
