### ISSUE TITLE
download links don't work

### ISSUE THREAD

**Issue by kalenkovich** [vasishth/bayescogsci#18]

**Comment by bnicenboim** [comment]
we don't have permission to make it" downloadable". Only this version is "open".

**Comment by kalenkovich** [comment]
Got it, thank you, @bnicenboim! Would you consider removing the links from https://vasishth.github.io/bayescogsci/book/ then?

**Comment by bnicenboim** [comment]
Yes! But I couldn't figure out how!

**Comment by kalenkovich** [comment]
Is it a bookdown::gitbook? If so, I found the following in the manual [here](https://bookdown.org/yihui/bookdown/html.html): 

> If you just want to suppress the download button, use download: false.

**Comment by bnicenboim** [comment]
ok, I managed to do it, thanks!
