### ISSUE TITLE
Feedback chapter 1

### ISSUE THREAD

**Issue by PLMir** [vasishth/bayescogsci#2]
Hello,

I am providing this feedback on the basis of the latest pdf version (as of September 1st), which I am reading as part of the SMLP2020. The pages I refer to are those printed on the pdf. 

p20, qnorm function: the description given for the function output is a little misleading. The text reads: "the above output says that the probability that the random variable... is 97.5%" but 97.5% is one of the arguments in the function, not the output of the function.  

p23, code block: 
- missing information about where to get the dataset (which I didn't find in the data folder on GitHub). 
- extra space here: f <- cbvpmf (ratingsbivar)   (although this is more about typographical consistency than an actual issue)
- the bivariate package is not indicated in the list of needed software

p27, I think equation (1.16) should read pY|X (y|x)? 

p31 & p32: I think Figures 1.8 and 1.9 have been mixed up. The caption of Figure 1.8 says there is a "positive correlation of -0.6" and the labels on the figure and the plots indicate a negative correlation. The caption of Figure 1.9 says there is a "negative correlation of -0.6", but the labels and the plots indicate a positive correlation. 

p34: typo: "taking the vector of standard deviatios" 
- the SIN package also wasn't listed as needed software

p35: The text says "we stick with our earlier example of n = 10 trials and k = 8 successes". => the earlier examples had k = 7. 

Best,
Patricia

**Comment by PLMir** [comment]
For the exercises of chapter 1, I only noted very minor typos: 
1.11.1.1: missing formatting for "pnorm"

1.11.1.2, 1.11.1.3, 1.11.4 : Missing colon after "getting" or "compute".

1.11.5, the grammar/syntax of the second bullet point (in the last paragraph) needs to be edited.

**Comment by vasishth** [comment]
Ch 1 typos fixed.
