### ISSUE TITLE
Typos "inter- cept" -> "intercepts" in 5.6 Exercises

### ISSUE THREAD

**Issue by CLRafaelR** [vasishth/bayescogsci#21]
I found minor typos in [5.6 Excercises](https://vasishth.github.io/bayescogsci/book/sec-HLMexercises.html#exercises-with-a-log-normal-likelihood): "inter- cept" should be "intercept".

See 
https://github.com/vasishth/bayescogsci/blob/ab00c8010e170b483121f7f87b9371b3ad597d7e/book/sec:HLMexercises.html#L1298
and
https://github.com/vasishth/bayescogsci/blob/ab00c8010e170b483121f7f87b9371b3ad597d7e/book/sec:HLMexercises.html#L1298

**Comment by bnicenboim** [comment]
thanks! It seems we had fixed this at some point
