### ISSUE TITLE
Section 3.1.1 duplicated code

### ISSUE THREAD

**Issue by Patrick-Wen** [vasishth/bayescogsci#22]
In section 3.3.1, the code `as_draws_df(fit_press)$b_Intercept %>% mean()` appeared twice. I am not sure if `as_draws_df(fit_press)$b_Intercept %>% sd()` is intended when the code appeared for the 2nd time.

**Comment by bnicenboim** [comment]
Thanks! Good catch, should I give you credit as "Patrick Wen"?

**Comment by Patrick-Wen** [comment]
That would be fine.

I have been enjoying reading the book recently, from which I learned so
much. Happy to help improve it. Thank you.

Patrick Wen

**Comment by vasishth** [comment]
Thank you Patrick. These corrections are greatly appreciated.
