### ISSUE TITLE
R code folder mssing 00 code 

### ISSUE THREAD

**Issue by michaelgaunt404** [vasishth/bayescogsci#25]
Your readme.txt indicates there should be a file name 00-loadlibraries.R. 

I assume it creates data frames and loads necessary libraries but it is missing from the zipfile. (see below)

![image](https://user-images.githubusercontent.com/60335544/159842816-9933342f-55fb-4e7f-b333-c83b9b6a646a.png)

![image](https://user-images.githubusercontent.com/60335544/159842838-d270af84-52c8-4ed9-9d04-8164d89ae8fe.png)

**Comment by bnicenboim** [comment]
Sorry for the long delay. I think this readme file is quite outdated, the data is now in a package. @vasishth, what should we do with this?

**Comment by vasishth** [comment]
@bnicenboim, @michaelgaunt404, I just edited the readme file. I think I can't put the readme in its final form yet, not till the book's source code becomes public (once the book is in press or published or in its final form).

@michaelgaunt404 the instructions for loading the libraries are in the introductory chapter.

I think we can close this.

**Comment by michaelgaunt404** [comment]
thank you and no problem!

**Comment by vasishth** [comment]
closing this issue. i think it is resolved.
