### ISSUE TITLE
typo in Chapter 8.1

### ISSUE THREAD

**Issue by Dallak** [vasishth/bayescogsci#26]
I guess there is a typo in the following excerpt:

 >  Why does the intercept assess the GM and why does the slope estimate the group difference? This is 
  the result of rescaling the sum contrast. The first factor level (F1) was coded as −0.5, and the second factor level (F1) as +0.5:

quoted from: https://vasishth.github.io/bayescogsci/book/basic-concepts-illustrated-using-a-two-level-factor.html#effectcoding.

 (F1) was repeated twice, where the second repetition was meant (F2)?

**Comment by bnicenboim** [comment]
thanks!
