### ISSUE TITLE
Equations in chapter 20.1.3 and 20.1.5

### ISSUE THREAD

**Issue by yadavhimanshu059** [vasishth/bayescogsci#28]
I think there is something wrong with the following equations. Can Bruno check?

[20.1.3 Fitting the log-normal race model](https://vasishth.github.io/bayescogsci/book/modeling-a-lexical-decision-task.html#fitting-the-log-normal-race-model)

Rather than trying to estimate all the censored observations, we integrate them out:

`P(T_censored) = ...`

**HY: In the above equation, the complementary CDF should correspond to the "non-word" accumulator when `choice=word`.**

[20.1.5 Dealing with contaminant responses](https://vasishth.github.io/bayescogsci/book/modeling-a-lexical-decision-task.html#sec:contaminant)

The second term of the likelihood represents the log-normal race model that occurs with probability `1-theta_c`. We use `p_lnrace(rt_n,choice_n)` as a shorthand for the following function (which we have already used in the models before): 

`p_lnrace(rt_n,choice_n) = ...`

**HY: Again, the word accumulator's likelihood should be multiplied with the complementary CDF of the "non-word" accumulator when `choice=word`.**

**HY: Finally, the equations with `\tag{20.1}` and `\tag{20.2}` are still in their latex form (probably some box command error).**

**Comment by bnicenboim** [comment]
thanks!
I've just fixed this, we'll update the html version soon.
