### ISSUE TITLE
Typos in 8.3, 9.1

### ISSUE THREAD

**Issue by elizabethpankratz** [vasishth/bayescogsci#29]
In [Section 8.3.5](https://vasishth.github.io/bayescogsci/book/sec-4levelFactor.html#an-alternative-to-contrasts-monotonic-effects):

> FIGURE 8.3: Conditional effects using the polinomial contrasts on the left side vs. assuming monotic effects on the right side.

polinomial -> polynomial
monotic -> monotonic

In [Section 9.1.1](https://vasishth.github.io/bayescogsci/book/sec-MR-ANOVA.html#nestedEffects):

> Regression coefficients estimate the GM, the difference for the main effect of word frequency (A) and the two differences (for B; i.e., simple main effects) within levels of word frequency (A).

I think that the variables might be switched around here, since this sentence follows the fixed effects of model `fit_Nest` that looks at a main effect of B and the differences for A nested within levels of B.

**Comment by bnicenboim** [comment]
Thanks! 
@danielschad , could you take a look at section 9.1.1?

**Comment by vasishth** [comment]
I have fixed all this now. Elizabeth was right, the factors got switched.
