### ISSUE TITLE
Feedback chapter 2

### ISSUE THREAD

**Issue by PLMir** [vasishth/bayescogsci#3]
Hi,

Here are the few errors I noticed in chapter 2: 

p50: "This becomes evidence" => "evident"
p52: In the conjungacy definition, the posterior is referred as y(theta|y), I think it should read p(theta|y)?
p55: "the extent to owhichh" => "which"
p.59, 2.4.3, maybe the likelihood function could be printed on a separate line, like the other equations in the exercises?
p59-60, equations 2.26, 2.27, 2.28, 2.29, the exponential elements are not showing properly
p61: "given this new data-point" => "data point"

- Patricia

**Comment by vasishth** [comment]
done
