### ISSUE TITLE
Suspected typo in the priors chapter

### ISSUE THREAD

**Issue by cfhammill** [vasishth/bayescogsci#34]
https://github.com/vasishth/bayescogsci/blob/5190e9514784b79ccf29aa4ee8785a7fc73826c2/book/ch-priors.html#L1567

In the section on prior elicitation it states that limits are chosen by the the expert, then:

> Because the quartiles are elicited before the median, this minimizes the effects of the “anchoring and adjustment heuristic” 

It goes on to say, then medians are estimated then quartiles, so I think the statement above should be "bounds are elicited before the median".

**Comment by vasishth** [comment]
fixed
