### ISSUE TITLE
Typos in 1.6.2

### ISSUE THREAD

**Issue by noestetie** [vasishth/bayescogsci#39]
I think there is a quotation mark misplaced in chapter 1.6.2. It says: 

> One occasionally encounters a singularity’’ warning when fitting hierarchical models...

**Comment by noestetie** [comment]
I think there is also an 'a' missing, as it should be 'about' and not 'bout'? This is in the same section 1.6.2:

> except that we are talking bout a bivariate distribution here.

**Comment by vasishth** [comment]
Thanks! Fixed. Regarding the first correction, that sentence has been removed from ch 1 as it appears perhaps too early.
