### ISSUE TITLE
[Ch 9 Bayes factors] `save_all_pars =TRUE` is deprecated

### ISSUE THREAD

**Issue by CLRafaelR** [vasishth/bayescogsci#5]
We have used `save_all_pars =TRUE` in `brms` formulae to calculate the Bayes Factor, but [the package documentation](https://cran.r-project.org/web/packages/brms/brms.pdf#page=187) (Ver 2.14.0, released on 2020.10.08) says that such a method has already been deprecated. `save_all_pars =TRUE` may have to be replaced with `save_pars = save_pars(all = TRUE)`.

**Comment by bnicenboim** [comment]
fixed
