### ISSUE TITLE
questions section 6.3

### ISSUE THREAD

**Issue by jwnki** [vasishth/bayescogsci#50]
I appreciate very much the discussion about deriving priors from meta-analyses. However, I have troubles understanding the part on how to transform these priors to log scale. I would love to know (maybe consider including this in the text?):

- how to arrive at the number 0.041 (I thought this was `log(445 +10) - log(445 - 10)`  but this is equal to  0.045 not 0.041), and at the 95% credible interval (i.e. how were the values [−0.079,0.145] derived)
- what the three code blocks below the sentence "The calculations are shown below" illustrate? The resulting numbers do not seem to be connected in a straight-forward way to the text which precedes them
- in these three code blocks, why do you divide `b`, `lower` and `upper` by 2?

**Comment by vasishth** [comment]
Wow, this entire section is really intransparent. I need to fix this. I am doing it now and will just comment on the changes.

**Comment by vasishth** [comment]
I think @bnicenboim has fixed all these issues. I just re-read the section and it seems clear to me.
