### ISSUE TITLE
Some typos from chapters 2-5

### ISSUE THREAD

**Issue by egurtzegi** [vasishth/bayescogsci#60]
Hi, here are some typos I found while reading the first 5 chapters (the page numbers are from the pdf):

- pg. 82: ( left at the end of a line: "normal distribution ("
- pg. 162: "We will obtain different estimate" -> either "a different" or "estimates".
- pg. 214: In footnote 3, "or (sometimes also" the parenthesis should precede "or" instead of "sometimes".
- pg. 248: "the use of mean" -> "the use of the mean"
- pg. 251: add closing parenthesis after "(which has dimensions nx2"

**Comment by vasishth** [comment]
Thank you! All fixed.
