### ISSUE TITLE
Duplication in chapter 6

### ISSUE THREAD

**Issue by inigourrestarazu** [vasishth/bayescogsci#61]
Hi (again)!

I spotted a duplication in chapter 6.

"of of": There's a sentence that says "standard deviation *of of* the truncated".

I cannot find them know in the online version, but in the pdf version I'm checking:
- There also was a wrong sign in the formulas of section 6.3. It said "exp(alpha + beta)  - exp(alpha **+** [INSTEAD OF MINUS] beta)".
- There's a *beta* spelled, with a hat on the *b*. I guess it was a backslash missing in the mathjax.

As said, I cannot find these two in the online version, so I guess you spotted it too. But just in case.

Thank you :)

**Comment by vasishth** [comment]
Thanks; we caught all of these in the final revisions.
