### ISSUE TITLE
Conditional probability and the weather

### ISSUE THREAD

**Issue by PhilipLoewen** [vasishth/bayescogsci#64]
I can nit-pick all day. Let me know when you want/need me to stop. :)

In Section 1.2, the current example loses some expressive power by describing a situation where the conditional probability is obviously 1. (That's the probability that the streets are wet given that it has been raining). Interchanging the events would be one simple fix: the probability that it has been raining given that the streets are wet is, perhaps, only 0.98 ... sometimes the city sends a street-washing truck along the road on a sunny day.

If you have the energy to review several paragraphs, I would suggest perhaps discussing the probability that it rains in the afternoon given that it rained in the morning. This alternative example is even more thought-provoking.

**Comment by vasishth** [comment]
Yes, when I teach from the book, I do bring up these variants. Actually, this example was inspired by a stay in Paris, where they aggressively wash the streets every morning, leading to wet streets every morning.
