### ISSUE TITLE
Truncating the Normal Distribution

### ISSUE THREAD

**Issue by PhilipLoewen** [vasishth/bayescogsci#66]
Here's a philosophical note, where the response will depend on what you want your students to prioritize.

I'm looking at 1.5.2. If the priority is to get students to practice `R`, finding _k_ as shown here is the way to go. In my classes, the priority is different: I want to give students intuitive and pictorial alternatives to algebra and computation, so I would prefer to start by noting that the graph of the Gaussian PDF has reflection symmetry across its peak. The axis of symmetry in the graph (namely, $x=\mu$) therefore gives both the mean and the median for the distribution. In particular, for _N(0,1)_, discarding half the picture means eliminating half the area under the curve, and that calls for multiplying the original PDF by _k=2_. Of course you know all this! I'm just advocating for a moment of reflection on the priorities that determine the style of explanation offered.

Related: For visually-oriented thinkers, it might be nice to mention in the description of discrete random variables that when we draw a bar-chart showing the PMF, the _total height of all the bars_ must be 1, whereas when we sketch the graph of a PDF for a continuous random variable, it's the _area under the curve_ that must be 1. Indeed, the link between area under the density graph and the probability attributed to the domain might be worth bringing forward more explicitly ... right now the text just starts using this definition at some point, without clearly stating it up front.

**Comment by vasishth** [comment]
Good idea. I added this. Thanks.
