### ISSUE TITLE
Table 1.3 Renders Incorrectly

### ISSUE THREAD

**Issue by PhilipLoewen** [vasishth/bayescogsci#67]
In the row labels of Table 1.3, the HTML entities for "|" show up explicitly instead of being rendered as vertical bars. This may be caused by unfortunate nesting of braces.

**Comment by vasishth** [comment]
Please keep these comments coming. I will address all the issues you open in late September. This week I am busy teaching at a summer school, and then plan to go hiking 14-24 Sept. After I get back, I will fix all the issues you open.

**Comment by PhilipLoewen** [comment]
Best wishes for another successful summer school and a pleasant time in the outdoors.

**Comment by vasishth** [comment]
I've alerted the first author. Thanks!
