### ISSUE TITLE
Suggestion for Ch 2: Plot the likelihood sooner

### ISSUE THREAD

**Issue by PhilipLoewen** [vasishth/bayescogsci#68]
I would personally find it helpful to see a plot of the [scaled] likelihood immediately after it is defined in subsection 2.2.1.

The likelihood function is available as soon as one has some data and a model for the parameter-dependent distribution that the data come from. As such, it is conceptually unrelated to the key ideas of "prior" and "posterior" discussed later, and readers may benefit from using a plot as a foundation for the next steps.

Newcomers to the subject may not recognize immediately that _the dashed curves representing scaled likelihood in all 4 panels of Figure 2.3 are identical_. Their understanding might be improved by saying this explicitly, and supplying a back-reference to a simple plot they had understood earlier could lock this idea in even tighter. For best results, I would suggest using the same line style that denotes the likelihood in Fig. 2.3 for a new plot in subsection 2.2.1

**Comment by vasishth** [comment]
I like to do that kind of stuff in the in-person lecture in real time. The book lays out the story for me, and then I add to it. I think that there is huge value in leaving out obvious things like these, to help the reader reflect on what they just read, and to help the reader meditate on a figure like 2.3. I think it builds what mathematicians call "mathematical maturity."
