### ISSUE TITLE
Error in chapter 4.1.2 (centering `load`)

### ISSUE THREAD

**Issue by awellis** [vasishth/bayescogsci#7]
There is a problem in 4.1.2: after centering the cognitive load variable. This results in `c_load = 0` for all observations, and leads to an estimate of around 0 for the regression coefficient

```
## Population-Level Effects: 
##           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept   701.35     22.53   657.27   745.91 1.00     3698     2707
## c_load        0.48    103.50  -202.44   196.80 1.00     3982     2682
## 
```

**Comment by bnicenboim** [comment]
Thanks, it's fixed in the new version that we'll release in a couple of weeks
