### ISSUE TITLE
Ch 2: Rephrasing for precision

### ISSUE THREAD

**Issue by PhilipLoewen** [vasishth/bayescogsci#70]
Right now the text in 2.2.4 says,

> ... we started with data (n=100,k=80) and a binomial likelihood, multiplied it with the prior θ∼Beta(4,4) ...

Inserting the extra words in bold below would add some precision:

> ... we started with data (n=100,k=80) and a binomial likelihood, multiplied it with **the density of** the prior θ∼Beta(4,4) ...

**Comment by vasishth** [comment]
Are we really multiplying with the density? The density would be a single number at a particular point lying between 0 and 1. The density of the prior doesn't have much meaning either (at least not to me). 

I think we are multiplying with the density function. I changed it to probability density function.
