### ISSUE TITLE
Ex 2.3: Illustration for a geometric random variable

### ISSUE THREAD

**Issue by PhilipLoewen** [vasishth/bayescogsci#71]
Current text:

> Suppose that we perform n independent trials until we get a success (e.g., a heads in a coin toss). For coin tosses, the possible outcomes could be, H, TH, .

If the idea is to stop when the coin first shows H, the suggested sample sequence does not conform. I suggest replacing the second sentence with this:

> For repeated coin tosses, observing T, T, H, ..., would correspond to a score of _n=3_.

(In the world of math, we put our decorative stars in a superscript position, so the updated parameters requested here would be denoted $a^{\*}$ and $b^{\*}$. If you also prefer this, there are opportunities both here and in later exercises. Coaxing markdown to achieve it is a little tricky: I had to backslash-escape the asterisk characters.)

**Comment by vasishth** [comment]
I fixed this. I am not sure what you mean about coaxing R Markdown to achieve this; I don't need a backslash in math mode to create a superscript.

**Comment by vasishth** [comment]
Fixed.
