### ISSUE TITLE
Ex 2.6 tune-up

### ISSUE THREAD

**Issue by PhilipLoewen** [vasishth/bayescogsci#73]
The variable $x$ often denotes a general real value, so it may be helpful to readers to emphasize the discrete-ness of a Poisson distribution by appending the restriction "for $x=0,1,2,\ldots$" to the definition of $f(x\vert\theta)$ displayed here.

The setup might be easier to track if the definition of $f$ were followed immediately by an extra sentence like this:

> Given $n$ independent observations of a Poisson random variable with rate parameter $\theta$, the maximum-likelihood estimator (MLE) for $\theta$ turns out to be $\bar\theta = \frac1n\sum_{i=1}^n x_i$. (Optional: Use calculus to prove this!)

Right now the text uses the notation $\bar x$ for the MLE, and I implicitly suggest the alternative $\bar\theta$ above: which one to pick is a pedagogical choice best left to the author. But in any case, the subscript indices on $x_i$ in the defining summation should be added.

I fear that the problem's last two bulleted requests are subtler than they look. The problem is that the sample mean (whether denoted by $\bar x$ or $\bar\theta$) actually depends on the number of samples, so the $n$-dependence on the right side of (2.12) is not confined to the coefficients in the weighted average shown there. I believe the requested conclusions still hold, but the reasons are not obvious. (Specifically, the Strong Law of Large Numbers promises that the empirical means computed from more and more samples will converge with probability 1 to $\theta$, the mean of the original distribution, and this could be used to argue that the jiggles in the computed values of $\bar x$ as $n$ increases don't spoil the general idea ... but that line of reasoning goes considerably beyond the level expected so far.) I'm not sure what to suggest about this. Definitely something that keeps this exercise in play: it's a nice one.

**Comment by vasishth** [comment]
Re your suggestion about adding the definition of the estimator; I now write:

> As an aside: Given $n$ independent observations of a Poisson random variable with rate parameter $\theta$, the maximum-likelihood estimator (MLE) for $\theta$ turns out to be $\hat{\theta} = \frac{\sum{i=1}^n x_i}{n}$. When we are talking about a particular sample of data, the maximum-likelihood estimate is computed using the formula for the estimator,  $\frac{\sum{i=1}^n x_i}{n}$, and is represented as $\bar{x}$.

I felt it's important for the reader to know that this fact is not directly needed for solving the problem; but I agree that the reader needs to know what $\bar{x}$ is.

Re your comment:

> I fear that the problem's last two bulleted requests are subtler than they look. The problem is that the sample mean (whether denoted by x ¯ or θ ¯ ) actually depends on the number of samples, so the n -dependence on the right side of (2.12) is not confined to the coefficients in the weighted average shown there. I believe the requested conclusions still hold, but the reasons are not obvious. (Specifically, the Strong Law of Large Numbers promises that the empirical means computed from more and more samples will converge with probability 1 to θ , the mean of the original distribution, and this could be used to argue that the jiggles in the computed values of x ¯ as n increases don't spoil the general idea

I actually didn't understand what you are saying here. What is (2,12)?

This exercise only tries to get people to understand that the posterior mean is a compromise between the prior mean and the MLE based on the sample. One can prove the weighted mean equation (2.35) regardless of what n is.

**Comment by PhilipLoewen** [comment]
On the online copy of the book I see on [github.io](https://vasishth.github.io/bayescogsci/book/ch-introBDA.html#sec-BDAexercises), the equation expressing _a*/b*_ is numbered (2.12).

I think I misinterpreted the intent of the question. I agree that the expression on the right side of equation (2.12) presents _a*/b*_ as a weighted average of two quantities, and that the weights put increasing emphasis on the values of _xbar_ as _n_ grows. That's what the first bullet asks, so all is well.

My incorrect reading was to think that the first bullet asked people to show that the right side converges to _xbar_ as _n_ tends to infinity. That would be questionable, for many reasons, but it reflects confusion on my part and not in the book. (The technical words in my original comment were to outline a proof that the right side converges to theta, the expected value of the data distribution, as _n_ tends to infinity. But now I realize that this was never requested.)

I'm still uneasy about the second bulleted request, though. The suggested conclusion does seem to rely on some kind of stable predictable behaviour of the sample means _xbar(n)_ as _n_ increases.

Let me focus all this into two concrete suggestions for Ex 2.6.

- Squeeze the sentence about "Specifically, what you have to prove ..." into the body of the first bulleted activity, and
- Fold in a note somewhere (perhaps outdented  after the first bullet) that, "You may assume the sample means _xbar_ converge to theta as _n_ increases."

**Comment by vasishth** [comment]
I feel that the convergence of \bar{x} to the true parameter as n increases is an orthogonal issue here. \bar{x} is a non-rigid designator here; it doesn't matter what the \bar{x} happens to be and it doesn't matter whether it is near the true value of the parameter or not. The point of the exercise is to see the relationship between the prior mean and MLE, and how these determine the posterior mean in this particular case. 

Thanks for your careful look at this.
