### ISSUE TITLE
"Copy" button grabs too much in online text

### ISSUE THREAD

**Issue by PhilipLoewen** [vasishth/bayescogsci#75]
In the version of Chapter 3 online at  `https://vasishth.github.io/bayescogsci/book/ch-compbda.html`, many isolated sections showing R code support a "Hide" button at the top left and a pop-up "Copy to Clipboard" button at the top right.

On my system, clicking "Copy to Clipboard" copies not only the desired R commands in the box, but also the 4-character string "Hide" from the label on the first button just mentioned. So in my experience, copy-paste into R is not quite seamless: I have to copy, paste, and then back up to remove "Hide" from the beginning of the input before pressing enter.

It's possible that this behaviour is an unlucky aspect of my setup that afflicts nobody else: I am using the Firefox 115.15.0esr browser on Debian Linux 12. Reporting anyway.

**Comment by vasishth** [comment]
Yes, others have complained about this too. I just asked them to copy manually :)

R Markdown and bookdown has been less than perfect. Knuth got it right with latex (more or less) but these modern tools are clunky. I assigned the issue to the first author but the book will come with all source code Rmd files). So maybe that is good enough.

**Comment by vasishth** [comment]
I will send you a physical copy :)
