### ISSUE TITLE
Book citation

### ISSUE THREAD

**Issue by edarin** [vasishth/bayescogsci#8]
This book is excellent. I would like to acknowledge it in one of my writing. How shall I do that?

**Comment by vasishth** [comment]
thanks. you can cite it as:

Bruno Nicenboim, Daniel J. Schad, and Shravan Vasishth. Introduction to Bayesian Data Analysis for Cognitive Science. 2021. Under contract with Chapman and Hall/CRC Statistics in the Social and Behavioral Sciences Series. 
URL: https://vasishth.github.io/bayescogsci/book/

**Comment by bnicenboim** [comment]
I think it would be a good idea to add the complete date as well since the book is changing. Maybe something like "Draft from 2021-07-28"
