### ISSUE TITLE
sec-pupil.html 4.1.2

### ISSUE THREAD

**Issue by themeo** [vasishth/bayescogsci#9]
The brms model should use the prior Normal+ (0, 1000) for sigma, right?

**Comment by bnicenboim** [comment]
yes, but that's what we do, isn't it?

    prior(normal(0, 1000), class = sigma),

**Comment by themeo** [comment]
Do you mean that having 'sigma' class automatically restricts the distribution to positive values only? I didn't think about this when commenting, but since it is isn't obvious, perhaps it would be worth commenting about it in a footnote? It is possible that it was already mentioned somewhere earlier, if yes, then sorry for making fuss. :)

**Comment by bnicenboim** [comment]
Yes, it's written but I guess we should remind the reader.
Thanks!
